### ISSUE TITLE
Add handling of node / edge styles (solid, dashed, dotted)

### ISSUE THREAD

**Issue by mstefaniuk** [mstefaniuk/graph-viz-d3-js#12]
Example shown on http://graphviz.it/#/ahoweSmq

**Comment by MarkRobbo** [comment]
This involves adding the [stroke-dasharray](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray) property to the svg elements (some hardcoded values for dashed and dotted would suffice eg 2,5 and 1,5)

**Comment by mstefaniuk** [comment]
It can be managed using CSS also for downloads when stylesheet is embedded in SVG as in https://github.com/mstefaniuk/graph-viz-d3-js/blob/master/src/js/stage.js#L79-L85

**Comment by MarkRobbo** [comment]
@mstefaniuk Thanks for the workaround tip, for the time being
