### ISSUE TITLE
Diagram doesn't display on Chrome / Safari (OS/X)

### ISSUE THREAD

**Issue by mstefaniuk** [mstefaniuk/graph-viz-d3-js#14]
Attempt to show [advent expression diagram](https://gist.github.com/mjpieters/29623e9585fd694cdcc5) causes "Parsing of xdot output failed"

**Comment by mstefaniuk** [comment]
It's related with mdaines/viz.js/issues/56. Huge diagrams causes `Uncaught RangeError: Maximum call stack size exceeded` when dot source is transformed to xdot.

**Comment by akinnee-gl** [comment]
It's working for me in Chrome

**Comment by mstefaniuk** [comment]
The case was on OSX Chrome and Safari. Please check `viz.js` issue for precise browser versions. Maybe it was fixed in newer versions so these can be closed.

**Comment by mstefaniuk** [comment]
It's a viz.js issue.
