### ISSUE TITLE
enable zoom/drag

### ISSUE THREAD

**Issue by logust79** [mstefaniuk/graph-viz-d3-js#16]
In `renderer.js`, `main = svg.append('g')` can be changed to `main = svg.append('g').append('g')`, so that one can use d3.behavior to zoom/drag the graph properly. Example code can be found on my fork.

**Comment by mstefaniuk** [comment]
@logust79 Could you create a pull request?

**Comment by logust79** [comment]
@mstefaniuk Yes, of course.
