### ISSUE TITLE
images

### ISSUE THREAD

**Issue by jschoch** [mstefaniuk/graph-viz-d3-js#2]
```
can you use html tags like <img>

```

**Comment by jschoch** [comment]
```
sorry, just noticed my <img> tag was truncated out

can you use anything like 

TitleNode [ label="FOO", image="http://placehold.it/140x100"] 

```

**Comment by mstefaniuk** [comment]
This project makes use of external Graphviz engine [viz.js](/mdaines/viz.js). I had originally use older version of it and now I have some obstacles to embed its newer versions in WebWorker. I would follow your issue when my editor would support images.

**Comment by mstefaniuk** [comment]
@jschoch As far I've checked there is no support in Graphviz for embedding images from the web address - only local files. I have no idea how it's handled by viz.js (version compiled to JS I use) but in xdot output there is no formatting information about image. Only URL is echoed but it is not enough to add it properly to graph.

**Comment by mstefaniuk** [comment]
It's related to mdaines/viz.js#50.

**Comment by mstefaniuk** [comment]
It is not supporter by viz.js so won't fix for now.
