### ISSUE TITLE
Change of license from LGPLv3 to something else?

### ISSUE THREAD

**Issue by tedyoung** [mstefaniuk/graph-viz-d3-js#21]
I understand the desire for people to contribute code back to this project, but the use of a [L]GPL license means that some larger, more conservative, companies won't use it at all and therefore won't be able to contribute back. Any thoughts on an Apache or MIT/BSD flavored license?

**Comment by mstefaniuk** [comment]
I will make it less strict with MIT license. Stay tuned.

**Comment by mstefaniuk** [comment]
I've just changed license. Enjoy!
