### ISSUE TITLE
renderer callback/promise

### ISSUE THREAD

**Issue by dmattsson** [mstefaniuk/graph-viz-d3-js#22]
First, thanks for this awesome project - it's exactly what I was looking for

I'm having troubles understanding how to execute a function after a chart has been rendered. I've been trying callbacks (e.g. below) and promises, but it doesn't seem to work.

`renderer.render(dotSource, function (err, resp) {
    if(!err) {
      postRender();
   }
  });`

**Comment by mstefaniuk** [comment]
There is no standard callback or promises API for that. Currently you can add only an error callback as shown in [renderer spec](/mstefaniuk/graph-viz-d3-js/blob/master/spec/renderer-spec.js#L54). API should be extended definetely - I will look into it within one or two weeks or maybe @dmattsson you can send a pull request?

**Comment by dmattsson** [comment]
Aha ok I understand! Yes it would definitely be a good addition.

If I get it to work I'll definitely make a pull request. I'm still a novice in JS though so I'm not sure if I got what it takes to do it the proper way.

Thanks again

**Comment by mstefaniuk** [comment]
It has been fixed. Now you can define handler using `renderer.renderHandler(callback)`.
