### ISSUE TITLE
quotes in graph labels break parsers

### ISSUE THREAD

**Issue by Pike** [mstefaniuk/graph-viz-d3-js#24]
I've got a simple testcase which breaks the dot/xdot parsers:

    digraph G {
      mynode [ label="Some \" quote" ];
    }

This is a totally fine graph for graphviz (and viz.js), but breaks the d3 hooks.

I have a local patch that adds this as a testcase to spec/directed, but not enough experience with peg.js to suggest a fix.

**Comment by mstefaniuk** [comment]
Please share your case as a comment.

**Comment by Pike** [comment]
Just the single node is all I needed to reproduce the bug. Yes, not all that directed ;-).

https://github.com/mstefaniuk/graph-viz-d3-js/compare/master...Pike:test-quote-issue-24 is my branch that just adds the test.
