### ISSUE TITLE
Is it possible to use the D3 renderer for an existing xdot file?

### ISSUE THREAD

**Issue by lifan0127** [mstefaniuk/graph-viz-d3-js#32]
As I understand this package will (1) validate/parse a dot file, (2) compute the layout (via viz.js) to output a xdot file, and then (3) use D3 to render an SVG.

If I have already generated the xdot file with GraphViz offline, can I skip steps 1-2 and just use the render to create the SVG directly? Thanks!

**Comment by mstefaniuk** [comment]
Sure, you can. It is performed in two steps:
* generating data structures for rendering (in webworker, https://github.com/mstefaniuk/graph-viz-d3-js/blob/master/src/js/transformer.js#L9-L10)
* rendering data structures using d3.js API (https://github.com/mstefaniuk/graph-viz-d3-js/blob/master/src/js/transformer.js#L9-L10)

**Comment by lifan0127** [comment]
Many thanks for your help! I was able to use the rendering functions for my existing xdot files.
