### ISSUE TITLE
Upgrade D3 to version 4

### ISSUE THREAD

**Issue by magjac** [mstefaniuk/graph-viz-d3-js#38]
I've started to adapt graph-viz-d3-js to D3 version 4.7.4. I will send you a pull request when I'm done.

If you want to do it yourself or have some reason why it shouldn't be done, please stop me soon, before I've put too much work into it.

**Comment by mstefaniuk** [comment]
I'm only encouraging you to do that.

**Comment by magjac** [comment]
Implemented with pull request https://github.com/mstefaniuk/graph-viz-d3-js/pull/39, but coverage decreased. I'll have a look at it later.
