### ISSUE TITLE
How to run coverage analysis locally?

### ISSUE THREAD

**Issue by magjac** [mstefaniuk/graph-viz-d3-js#40]
Tried coveralls and got the following problem:

```
node_modules/.bin/grunt coveralls
Running "coveralls:firefox" (coveralls) task
>> Failed to submit 'karma/lcov.info' to coveralls: Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
>> WARNING: Failed to submit coverage results to coveralls

Done, without errors.
```
I looked at https://github.com/nickmerwin/node-coveralls#usage:
> If you're running locally, you must have a .coveralls.yml file, as documented in their documentation, with your repo_token in it; or, you must provide a COVERALLS_REPO_TOKEN environment-variable on the command-line.

But I can't find that file or any token to set.

**Comment by mstefaniuk** [comment]
Coverage is calculated automatically during each run of karma (as defined in `karma.conf.js`):
```js
reporters: ['jasmine-diff', 'progress', 'coverage', 'html']
```
and it lands in karma directory. What you try to run is publishing coverage report to coveralls but it should not be performed locally but only on TravisCI. I would suggest to use WebStorm or other IDE and run Karma with coverage and then use in-built coverage viewer.

**Comment by magjac** [comment]
Thanks. I have no experience in WebStorm, other IDE or Karma. Can you give directions?

I tried lcov, but don't know how to get the details:

```
lcov -l karma/lcov.info
Reading tracefile karma/lcov.info
                     |Lines       |Functions  |Branches
Filename             |Rate     Num|Rate    Num|Rate     Num
===========================================================
[./src/js/]
dot-checker.js       | 100%      8| 100%     3|    -      0
palette.js           | 100%     12| 100%    10|    -      0
pegast.js            | 100%      4|75.0%     4|    -      0
renderer.js          | 100%     20| 100%     6|    -      0
stage.js             |97.2%    107|91.7%    36|    -      0
styliseur.js         |95.0%     20| 100%     4|    -      0
transformer.js       |97.5%     40|94.1%    17|    -      0
===========================================================
               Total:|97.6%    211|93.8%    80|    -      0
```

**Comment by mstefaniuk** [comment]
Currently Karma launches coverage plugin with option `type: 'lcovonly'`. If you want something much more human readable you should use `html` option or other as described on https://github.com/karma-runner/karma-coverage#advanced-multiple-reporters.
