### ISSUE TITLE
Deletes of duplicate edges aren't handled properly

### ISSUE THREAD

**Issue by ekmett** [mstefaniuk/graph-viz-d3-js#52]
Take a simple graph with a redundant edge, such as

```
digraph {
	x -> y;
	x -> y;
}
```

and delete the second `x -> y` edge. It'll leave a "zombie" edge in the UI that you can't get rid of.

**Comment by mstefaniuk** [comment]
Let me look into it.

**Comment by mstefaniuk** [comment]
Seems to be fixed in the latest release (0.9.50). Online fiddling website is also upgraded (http://graphviz.it).
